 ### Московский Авиационый Институт 
 #### (НАЦИОНАЛЬНЫЙ ИССЛЕДОВАТЕЛЬСКИЙ УНИВЕРСИТЕТ)
 #### Лабороторная работа №3
 #### По дисциплине "Программирование на Python"
 #### На тему "Работа с библиотекой NumPy"
 #### Выполнил студент группы Т12о-101М: Трусова В.Л.
 #### Работу принял: Поповкин А.В.
 ##### Дата: 21.11.2020
 ##### Москва, 2020г.

In [34]:
import numpy as np

Дан вектор [1, 2, 3, 4, 5], построить новый вектор с тремя нулями между каждым значением

In [6]:
mas_num = np.array([1,2,3,4,5])
z_num = 3
mas = np.zeros(len(mas_num) + (len(mas_num)-1)*(z_num)) #массив 0-ей
mas[::z_num+1] = mas_num #добавляем значения из исходного
print(mas)

[1. 0. 0. 0. 2. 0. 0. 0. 3. 0. 0. 0. 4. 0. 0. 0. 5.]


Поменять 2 строки в матрице

In [4]:
mas = np.arange(25).reshape(5,5)
print(mas)
mas[[0,3]] = mas[[1,0]]
print(mas)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]
[[ 5  6  7  8  9]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [ 0  1  2  3  4]
 [20 21 22 23 24]]


Рассмотрим набор из 10 троек, описывающих 10 треугольников (с общими вершинами), найти 
множество уникальных отрезков, составляющих все треугольники

In [36]:
faces = np.random.randint(0,15,(10,3))
F = np.roll(faces.repeat(2,axis=1),-1,axis=1)
F = F.reshape(len(F)*3,2)
F = np.sort(F,axis=1)
G = F.view( dtype=[('p0',F.dtype),('p1',F.dtype)] )
G = np.unique(G)
print(G)

[(0,  2) (0,  4) (0,  6) (0,  8) (0, 10) (0, 11) (0, 14) (1,  3) (1, 14)
 (2,  6) (2,  8) (2,  9) (2, 11) (2, 13) (3,  6) (3,  9) (3, 14) (4, 14)
 (6,  6) (6, 10) (6, 11) (6, 13) (9, 13) (9, 14)]


Дан массив C; создать массив A, что np.bincount(A) == C

In [10]:
C = np.bincount([1,1,2,3,4,4,6])
A = np.repeat(np.arange(len(C)), C)
print((np.bincount(A) == C).any())
print(A)
print(C)

True
[1 1 2 3 4 4 6]
[0 2 1 1 2 0 1]


Посчитать среднее, используя плавающее окно

In [31]:
def moving_average(a, n=3):
    ret = np.cumsum(a, dtype=float)
    ret[n:] = ret[n:] - ret[:-n]
    return ret[n - 1:] / n

print(moving_average(np.arange(5), 2))

[0.5 1.5 2.5 3.5]


Дан вектор Z, построить матрицу, первая строка которой (Z[0],Z[1],Z[2]), каждая последующая 
сдвинута на 1 (последняя (Z[-3],Z[-2],Z[-1]))

In [23]:
from numpy.lib import stride_tricks

def rolling(a, window):
    shape = (a.size - window + 1, window)
    strides = (a.itemsize, a.itemsize)
    return stride_tricks.as_strided(a, shape=shape, strides=strides)
mas = rolling(np.arange(10), 3)
print(mas)

[[0 1 2]
 [1 2 3]
 [2 3 4]
 [3 4 5]
 [4 5 6]
 [5 6 7]
 [6 7 8]
 [7 8 9]]


Инвертировать булево значение, или поменять знак у числового массива без создания нового

In [60]:
log_mas = np.random.randint(0,1,10)
print(log_mas)
print(np.logical_not(log_mas, out=log_mas))

num_mas = np.random.uniform(-1.0,1.0,10)
print(num_mas)
print(np.negative(num_mas, out=num_mas))

[0 0 0 0 0 0 0 0 0 0]
[1 1 1 1 1 1 1 1 1 1]
[-0.91209463  0.90102978  0.45082633  0.9155636  -0.43846891  0.39899843
 -0.17445358 -0.73145796 -0.77008534  0.5183664 ]
[ 0.91209463 -0.90102978 -0.45082633 -0.9155636   0.43846891 -0.39899843
  0.17445358  0.73145796  0.77008534 -0.5183664 ]


Посчитать ранг матрицы

In [36]:
mas = np.random.uniform(0,5,(3,3))
print(mas)
print(np.linalg.matrix_rank(mas))

[[4.95538377 3.53414387 4.94552021]
 [2.52605671 3.1759111  0.23118649]
 [3.11123708 4.7934422  0.72356378]]
3


Найти наиболее частое значение в массиве

In [41]:
mas = np.random.randint(0,5,15)
print(*mas)
print(np.bincount(mas).argmax())

4 2 3 0 4 3 3 4 0 4 3 0 2 2 0
0


Извлечь все смежные 3x3 блоки из 10x10 матрицы

In [24]:
from numpy.lib import stride_tricks
mas = np.random.randint(0,5,(10,10))
n = 3
i = 1 + (mas.shape[0] - n)
j = 1 + (mas.shape[1] - n)
res = stride_tricks.as_strided(mas, shape=(i, j, n, n), strides=mas.strides + mas.strides)
#возвращает представление массива с указанной формой и смещением байтов
print(res)

[[[[4 1 2]
   [0 3 4]
   [1 3 2]]

  [[1 2 1]
   [3 4 2]
   [3 2 0]]

  [[2 1 1]
   [4 2 4]
   [2 0 2]]

  [[1 1 4]
   [2 4 4]
   [0 2 3]]

  [[1 4 1]
   [4 4 2]
   [2 3 0]]

  [[4 1 0]
   [4 2 2]
   [3 0 1]]

  [[1 0 0]
   [2 2 4]
   [0 1 3]]

  [[0 0 2]
   [2 4 1]
   [1 3 1]]]


 [[[0 3 4]
   [1 3 2]
   [0 1 1]]

  [[3 4 2]
   [3 2 0]
   [1 1 4]]

  [[4 2 4]
   [2 0 2]
   [1 4 2]]

  [[2 4 4]
   [0 2 3]
   [4 2 2]]

  [[4 4 2]
   [2 3 0]
   [2 2 2]]

  [[4 2 2]
   [3 0 1]
   [2 2 0]]

  [[2 2 4]
   [0 1 3]
   [2 0 3]]

  [[2 4 1]
   [1 3 1]
   [0 3 3]]]


 [[[1 3 2]
   [0 1 1]
   [2 2 3]]

  [[3 2 0]
   [1 1 4]
   [2 3 3]]

  [[2 0 2]
   [1 4 2]
   [3 3 0]]

  [[0 2 3]
   [4 2 2]
   [3 0 1]]

  [[2 3 0]
   [2 2 2]
   [0 1 3]]

  [[3 0 1]
   [2 2 0]
   [1 3 0]]

  [[0 1 3]
   [2 0 3]
   [3 0 3]]

  [[1 3 1]
   [0 3 3]
   [0 3 2]]]


 [[[0 1 1]
   [2 2 3]
   [3 4 2]]

  [[1 1 4]
   [2 3 3]
   [4 2 2]]

  [[1 4 2]
   [3 3 0]
   [2 2 0]]

  [[4 2 2]
   [3 0 1]
   [2 0 3]]

  [[2 2 2]
   

Рассмотрим множество матриц (n,n) и множество из p векторов (n,1). 
Посчитать сумму p произведений матриц (результат имеет размерность (n,1))

In [46]:
p, n = 10, 20
mat = np.ones((p,n,n))
vec = np.ones((p,n,1))
res = np.tensordot(mat, vec, axes=[[0, 2], [0, 1]])
print(res)

[[200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]]


Дан массив 16x16, посчитать сумму по блокам 4x4

In [17]:
mas = np.ones((16,16))
k = 4
sum_ = np.add.reduceat(np.add.reduceat(mas, np.arange(0, mas.shape[0], k), axis=0),
                                       np.arange(0, mas.shape[1], k), axis=1)
#reduceat - получениe суммирования столбцов массива
print(sum_)

[[16. 16. 16. 16.]
 [16. 16. 16. 16.]
 [16. 16. 16. 16.]
 [16. 16. 16. 16.]]


Найти n наибольших значений в массиве

In [50]:
mas = np.arange(10000)
np.random.shuffle(mas)
n = 5

print (mas[np.argpartition(-mas,n)[:n]]) #возвращает массив индексов элементов

[9998 9997 9999 9996 9995]


Построить прямое произведение массивов (все комбинации с каждым элементом)

In [52]:
def cartesian(arrays):
    arrays = [np.asarray(a) for a in arrays] #преобразует последовательность в массив
    shape = map(len, arrays)

    ix = np.indices(shape, dtype=int)#возвращает координатную сетку
    ix = ix.reshape(len(arrays), -1).T

    for n, arr in enumerate(arrays):
        ix[:, n] = arrays[n][ix[:, n]]

    return ix

print(cartesian(([1, 2, 3], [4, 5])))

[[1 4]
 [1 5]
 [2 4]
 [2 5]
 [3 4]
 [3 5]]


Даны 2 массива A (8x3) и B (2x2). 
Найти строки в A, которые содержат элементы из каждой строки в B, независимо от порядка 
элементов в B

In [33]:
A = np.random.randint(0,5,(8,3))
B = np.random.randint(0,5,(2,2))
print(A)
print(B)
C = (A[..., np.newaxis, np.newaxis] == B)
rows = (C.sum(axis=(1,2,3)) >= B.shape[1]).nonzero()[0]
print(rows)

[[3 2 1]
 [2 4 2]
 [0 1 2]
 [4 0 4]
 [1 2 1]
 [2 3 4]
 [1 4 3]
 [4 0 0]]
[[2 1]
 [1 4]]
[0 1 2 3 4 5 6]


Дана 10x3 матрица, найти строки из неравных значений (например [2,2,3])

In [66]:
mas = np.random.randint(0,2,(10,3))
eq = np.logical_and.reduce(mas[:,1:] == mas[:,:-1], axis=1)
unique = mas[~eq]
print(mas)
print(unique)

[[1 0 1]
 [0 0 1]
 [0 0 1]
 [0 0 1]
 [0 0 0]
 [1 1 1]
 [1 0 0]
 [0 1 0]
 [1 0 1]
 [1 0 0]]
[[1 0 1]
 [0 0 1]
 [0 0 1]
 [0 0 1]
 [1 0 0]
 [0 1 0]
 [1 0 1]
 [1 0 0]]


Преобразовать вектор чисел в матрицу бинарных представлений

In [67]:
mas = np.array([0, 1, 2, 3, 15, 16, 32, 64, 128], dtype=np.uint8)
print(np.unpackbits(mas[:, np.newaxis], axis=1))

[[0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 1]
 [0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 1 1]
 [0 0 0 0 1 1 1 1]
 [0 0 0 1 0 0 0 0]
 [0 0 1 0 0 0 0 0]
 [0 1 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0]]


Дан двумерный массив. Найти все различные строки

In [15]:
mas = np.random.randint(0, 2, (6,3))
print(mas)
T = np.ascontiguousarray(mas).view(np.dtype((np.void, mas.dtype.itemsize * mas.shape[1])))
_, idx = np.unique(T, return_index=True) #находит уникальные элементы массива и их индексы
u_mas = mas[idx]
print(u_mas)

[[0 0 0]
 [0 0 0]
 [0 1 1]
 [1 1 0]
 [1 1 0]
 [1 0 1]]
[[0 0 0]
 [0 1 1]
 [1 0 1]
 [1 1 0]]


Даны векторы A и B, написать einsum эквиваленты функций inner, outer, sum и mul

In [87]:
a = np.arange(10)
b = np.arange(10)

print('A:', a)
print('B:', b)
print('sum(A):', np.einsum('i->', a)) #применяет правила суммирования Эйнштейна
print('A * B: ', np.einsum('i,i->i', a, b)) #'i,i->i' - индексы для суммирования
print('inner(A, B): ', np.einsum('i,i', a, b))
print('outer(A, B): \n' , np.einsum('i,j', a, b))

A: [0 1 2 3 4 5 6 7 8 9]
B: [0 1 2 3 4 5 6 7 8 9]
sum(A): 45
A * B:  [ 0  1  4  9 16 25 36 49 64 81]
inner(A, B):  285
outer(A, B): 
 [[ 0  0  0  0  0  0  0  0  0  0]
 [ 0  1  2  3  4  5  6  7  8  9]
 [ 0  2  4  6  8 10 12 14 16 18]
 [ 0  3  6  9 12 15 18 21 24 27]
 [ 0  4  8 12 16 20 24 28 32 36]
 [ 0  5 10 15 20 25 30 35 40 45]
 [ 0  6 12 18 24 30 36 42 48 54]
 [ 0  7 14 21 28 35 42 49 56 63]
 [ 0  8 16 24 32 40 48 56 64 72]
 [ 0  9 18 27 36 45 54 63 72 81]]
