 ### Московский Авиационый Институт 
 #### (НАЦИОНАЛЬНЫЙ ИССЛЕДОВАТЕЛЬСКИЙ УНИВЕРСИТЕТ)
 #### Лабороторная работа №2
 #### По дисциплине "Программирование на Python"
 #### На тему "Работа с библиотекой NumPy"
 #### Выполнил студент группы Т12о-101М: Трусова В.Л.
 #### Работу принял: Поповкин А.В.
 ##### Дата: 14.11.2020
 ##### Москва, 2020г.

Перемножить матрицы 5x3 и 3x2

In [2]:
import numpy as np
np.dot(np.ones((5,3)), np.ones((3,2)))

array([[3., 3.],
       [3., 3.],
       [3., 3.],
       [3., 3.],
       [3., 3.]])

Дан массив, поменять знак у элементов, значения которых между 3 и 8

In [29]:
mas = np.arange(11)
mas[(3 < mas) & (mas < 8)] *= -1
print(mas)

[ 0  1  2  3 -4 -5 -6 -7  8  9 10]


Создать 5x5 матрицу со значениями в строках от 0 до 4

In [7]:
mas = np.zeros((5,5))
mas += np.arange(5)
print(mas)

[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]


Есть генератор, сделать с его помощью массив

In [66]:
def generate():
    for x in range(10):
        yield x #ключевое слово для генератора
mas = np.fromiter(generate(),dtype=int)#создает одномерный массив
print(mas)

[0 1 2 3 4 5 6 7 8 9]


Создать вектор размера 10 со значениями от 0 до 1, не включая ни то, ни другое

In [15]:
np.linspace(0,1,12)[1:-1]

array([0.09090909, 0.18181818, 0.27272727, 0.36363636, 0.45454545,
       0.54545455, 0.63636364, 0.72727273, 0.81818182, 0.90909091])

Отсортировать вектор

In [16]:
v = np.random.random(10)
v.sort()
print(v)

[0.07447219 0.07863515 0.16775993 0.17031375 0.35616985 0.69923925
 0.7304559  0.82652353 0.93221227 0.98983517]


Проверить, одинаковы ли 2 numpy массива

In [23]:
mas1 = np.random.randint(0,2,5)
mas2 = np.random.randint(0,2,5)
equal = np.allclose(mas1,mas2) # поэлементно сравниваем 
print(equal)

False


Сделать массив неизменяемым

In [24]:
mas = np.zeros(10)
mas.flags.writeable = False
mas[0] = 1

ValueError: assignment destination is read-only

Дан массив 10x2 (точки в декартовой системе координат), преобразовать в полярную

In [30]:
mas_c = np.random.random((10,2))
x,y = mas_c[:,0], mas_c[:,1]
r = np.hypot(x, y) # полярный радиус
t = np.arctan2(y,x) # полярный угол (рад.)
print(r)
print(t)

[0.28486215 0.6783659  1.12847917 0.42526633 0.57058144 0.57567946
 0.27489013 0.95332725 0.64203053 0.04070026]
[0.15789594 0.54248061 0.5300066  1.20060689 0.63020142 0.57590557
 1.39743718 1.52143499 1.14510147 0.08682116]


Заменить максимальный элемент на ноль

In [26]:
mas = np.random.random(10)
print(mas)
mas[mas.argmax()] = 0 # получаем индекс макс. эл-та и заменяем его значение 0
print(mas)

[0.34901999 0.78534328 0.44982194 0.78293311 0.13888667 0.68514517
 0.16056521 0.32598416 0.48711648 0.17321319]
[0.34901999 0.         0.44982194 0.78293311 0.13888667 0.68514517
 0.16056521 0.32598416 0.48711648 0.17321319]


Создать структурированный массив с координатами x, y на сетке в квадрате [0,1]x[0,1]

In [27]:
mas = np.zeros((10,10), [('x',float),('y',float)])
mas['x'], mas['y'] = np.meshgrid(np.linspace(0,1,10), np.linspace(0,1,10))
# создает список массивов координатных сетокдля указанных одномерных массивов
print(mas)

[[(0.        , 0.        ) (0.11111111, 0.        )
  (0.22222222, 0.        ) (0.33333333, 0.        )
  (0.44444444, 0.        ) (0.55555556, 0.        )
  (0.66666667, 0.        ) (0.77777778, 0.        )
  (0.88888889, 0.        ) (1.        , 0.        )]
 [(0.        , 0.11111111) (0.11111111, 0.11111111)
  (0.22222222, 0.11111111) (0.33333333, 0.11111111)
  (0.44444444, 0.11111111) (0.55555556, 0.11111111)
  (0.66666667, 0.11111111) (0.77777778, 0.11111111)
  (0.88888889, 0.11111111) (1.        , 0.11111111)]
 [(0.        , 0.22222222) (0.11111111, 0.22222222)
  (0.22222222, 0.22222222) (0.33333333, 0.22222222)
  (0.44444444, 0.22222222) (0.55555556, 0.22222222)
  (0.66666667, 0.22222222) (0.77777778, 0.22222222)
  (0.88888889, 0.22222222) (1.        , 0.22222222)]
 [(0.        , 0.33333333) (0.11111111, 0.33333333)
  (0.22222222, 0.33333333) (0.33333333, 0.33333333)
  (0.44444444, 0.33333333) (0.55555556, 0.33333333)
  (0.66666667, 0.33333333) (0.77777778, 0.33333333)
  (0.8888

Из двух массивов сделать матрицу Коши C (Cij = 1/(xi - yj))

In [31]:
x = np.arange(8)
y = x + 0.5
c = 1.0 / np.subtract.outer(x, y) # поэлементная разность значений массивов
print(np.linalg.det(c)) # детерминант матрицы (для м. Коши !=0)

3638.1636371179666


Найти минимальное и максимальное значение, принимаемое каждым числовым типом numpy напечатать все значения в массиве

In [10]:
mas = []
for dtype in [np.int8, np.int32, np.int64]: #для целых чисел
   mas.append(np.iinfo(dtype).min)
   mas.append(np.iinfo(dtype).max)
for dtype in [np.float32, np.float64]: #для вещественных чисел
   mas.append(np.finfo(dtype).min)
   mas.append(np.finfo(dtype).max)
print(*mas, sep='\n')

-128
127
-2147483648
2147483647
-9223372036854775808
9223372036854775807
-3.4028235e+38
3.4028235e+38
-1.7976931348623157e+308
1.7976931348623157e+308


Найти ближайшее к заданному значению число в заданном массиве

In [11]:
mas = np.arange(100)
v = np.random.uniform(0,100) #возвращает число из заданного промежутка
index = (np.abs(mas-v)).argmin() #находим индекс числа с минимальным отклонением от заданного
print(mas[index])

63


Создать структурированный массив, представляющий координату (x,y) и цвет (r,g,b)

In [10]:
mas = np.zeros(10, [ ('position', [ ('x', float, 1),
                                   ('y', float, 1)]),
                    ('color',    [ ('r', float, 1),
                                   ('g', float, 1),
                                   ('b', float, 1)])])
print(mas)

[((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))]


<ipython-input-10-e2919c53721a>:1: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  mas = np.zeros(10, [ ('position', [ ('x', float, 1),


Дан массив (100,2) координат, найти расстояние от каждой точки до каждой

In [36]:
import scipy.spatial

mas = np.random.random((10,2))
dis = scipy.spatial.distance.cdist(mas,mas) 
#вычисляем дистанцию между каждой парой входных массивов
print(dis)

[[0.         0.7754787  0.85080628 0.59567091 0.26715865 0.69872213
  0.66924329 0.76099008 0.18679416 0.21175661]
 [0.7754787  0.         0.24488967 0.9379096  0.60921476 0.0926713
  0.61356011 0.15946841 0.69067591 0.67746031]
 [0.85080628 0.24488967 0.         1.13356849 0.62407268 0.31414266
  0.84271753 0.40431845 0.71824129 0.69834019]
 [0.59567091 0.9379096  1.13356849 0.         0.790256   0.84603888
  0.39353138 0.82138399 0.7515711  0.77090296]
 [0.26715865 0.60921476 0.62407268 0.790256   0.         0.55368231
  0.73298306 0.64666111 0.09572422 0.07429912]
 [0.69872213 0.0926713  0.31414266 0.84603888 0.55368231 0.
  0.53027942 0.11736673 0.62878438 0.61797329]
 [0.66924329 0.61356011 0.84271753 0.39353138 0.73298306 0.53027942
  0.         0.47051874 0.74348013 0.7518571 ]
 [0.76099008 0.15946841 0.40431845 0.82138399 0.64666111 0.11736673
  0.47051874 0.         0.71408852 0.70608702]
 [0.18679416 0.69067591 0.71824129 0.7515711  0.09572422 0.62878438
  0.74348013 0.714088

Преобразовать массив из float в int

In [39]:
mas = np.arange(10, dtype=np.float32)
print(mas)
mas = mas.astype(np.int32, copy=False) #преобразует тип входного массива
print(mas)

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]
[0 1 2 3 4 5 6 7 8 9]


Дан файл:
1,2,3,4,5
6,,,7,8
,,9,10,11
Как прочитать его?

In [15]:
import re
with open('some_num.txt', 'r') as f:
    str_ = f.read()
    num = re.findall('[0-9]+', str_) #находим все числа
    f.close() 
print(*num)

1 2 3 4 5 6 7 8 9 10 11


Каков эквивалент функции enumerate для numpy массивов?

In [13]:
mas = np.arange(9).reshape(3,3)
for index, value in np.ndenumerate(mas): #возвращающает пары (индекс элементa, значение)
    print(index, value)
for index in np.ndindex(mas.shape): #возвращающает индексы элементов в массиве заданной формы
    print(index, mas[index])

(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8
(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8


Сформировать 2D массив с распределением Гаусса

In [17]:
x, y = np.meshgrid(np.linspace(-1,1,10), np.linspace(-1,1,10))
d = np.hypot(x, y)
sigma, mu = 0.7, 0.0 #дисперсия, МО
g = np.exp(-((d - mu) ** 2 / (2.0 * sigma ** 2))) #распределение Гаусса
print(g)

[[0.12992261 0.19442824 0.26306636 0.32181229 0.35593548 0.35593548
  0.32181229 0.26306636 0.19442824 0.12992261]
 [0.19442824 0.29096046 0.39367691 0.48158977 0.53265487 0.53265487
  0.48158977 0.39367691 0.29096046 0.19442824]
 [0.26306636 0.39367691 0.53265487 0.65160321 0.7206956  0.7206956
  0.65160321 0.53265487 0.39367691 0.26306636]
 [0.32181229 0.48158977 0.65160321 0.79711416 0.88163573 0.88163573
  0.79711416 0.65160321 0.48158977 0.32181229]
 [0.35593548 0.53265487 0.7206956  0.88163573 0.97511949 0.97511949
  0.88163573 0.7206956  0.53265487 0.35593548]
 [0.35593548 0.53265487 0.7206956  0.88163573 0.97511949 0.97511949
  0.88163573 0.7206956  0.53265487 0.35593548]
 [0.32181229 0.48158977 0.65160321 0.79711416 0.88163573 0.88163573
  0.79711416 0.65160321 0.48158977 0.32181229]
 [0.26306636 0.39367691 0.53265487 0.65160321 0.7206956  0.7206956
  0.65160321 0.53265487 0.39367691 0.26306636]
 [0.19442824 0.29096046 0.39367691 0.48158977 0.53265487 0.53265487
  0.48158977 0

Случайно расположить p элементов в 2D массив

In [25]:
n = 5
p = 2
mas = np.zeros((n,n))
np.put(mas, np.random.choice(range(n*n), p, replace=False), 1)
#число, кол-во эл-ов, без повтора
#случайная выборка из значений заданного массива
print(mas)

[[0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


Отнять среднее из каждой строки в матрице

In [28]:
x = np.random.rand(2, 2) #случайно заполняем 0..1
y = x - x.mean(axis=1, keepdims=True) #результат - массив с размером исходного массива
print(x)
print(y)

[[0.35669195 0.55945978]
 [0.6822206  0.40567254]]
[[-0.10138392  0.10138392]
 [ 0.13827403 -0.13827403]]


Отсортировать матрицу по n-ому столбцу

In [33]:
mas = np.random.randint(0,10,(3,3))
n = 2 
print(mas)
print(mas[mas[:,n].argsort()])#сортировка элементов массива вдоль указанной оси 

[[0 3 3]
 [1 0 1]
 [8 2 5]]
[[1 0 1]
 [0 3 3]
 [8 2 5]]


Определить, есть ли в 2D массиве нулевые столбцы

In [24]:
mas = np.random.randint(0,3,(3,10))
print(mas)
print((~mas.any(axis=0)).any()) #проверяем столбцы матрицы

[[0 1 1 1 0 0 1 1 0 1]
 [0 1 2 1 2 1 2 2 0 0]
 [0 1 2 0 0 2 0 2 1 1]]
True


Дан массив, добавить 1 к каждому элементу с индексом, заданным в другом массиве (осторожно с повторами)

In [48]:
mas = np.ones(10)
inc = np.random.randint(0,len(mas),20)
mas += np.bincount(inc, minlength=len(mas)) 
#возвращает число вхождений
#последовательность целых положительных чисел, минимальное значение длины выходного массива
print(inc)
print(mas)

[1 5 2 1 9 7 1 4 0 4 7 2 5 3 7 3 4 7 6 8]
[2. 4. 3. 3. 4. 3. 2. 5. 2. 2.]


Дан массив (w,h,3) (картинка) dtype=ubyte, посчитать количество различных цветов

In [10]:
w,h = 16,16
i = np.random.randint(0, 2, (h,w,3)).astype(np.ubyte)
f = i[...,0] * 256 * 256 + i[...,1] * 256 + i[...,2]
n = len(np.unique(f))
print(n)

4


Дан четырехмерный массив, посчитать сумму по последним двум осям

In [56]:
mas = np.random.randint(0,10, (3,4,3,4))
sum_ = mas.reshape(mas.shape[:-2] + (-1,)).sum(axis=-1)
print(sum_)

[[41 46 41 54]
 [46 29 60 51]
 [57 58 49 52]]


Найти диагональные элементы произведения матриц

In [62]:
mas_1 = np.random.randint(0,10,(3,3))
mas_2 = np.random.randint(0,10,(3,3))
print(mas_1)
print(mas_2)
print(np.diag(np.dot(mas_1, mas_2)))

[[2 5 7]
 [8 5 8]
 [6 5 7]]
[[1 9 2]
 [7 4 9]
 [2 5 6]]
[ 51 132  99]
